-- AlterTable
ALTER TABLE "ChatMessage" DROP COLUMN "text",
DROP COLUMN "imageUrl",
ADD COLUMN     "ciphertext" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "iv" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "tag" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "keyVersion" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "ChatMessage" ALTER COLUMN "ciphertext" DROP DEFAULT;
ALTER TABLE "ChatMessage" ALTER COLUMN "iv" DROP DEFAULT;
ALTER TABLE "ChatMessage" ALTER COLUMN "tag" DROP DEFAULT;
